<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Position;
use AppBundle\Entity\User;
use AppBundle\Entity\PositionRankingHistory;

/**
 * PositionRankingHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionRankingHistoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function addNewHistoryRecord($data, $user, $position)
	{
		$em = $this->getEntityManager();

		$puzzleResult = ($data->puzzleResult == 'true') ? 1 : 0;

                $historyRecord = new PositionRankingHistory();
                $historyRecord->setPositionRanking($data->positionRanking);
                $historyRecord->setSolveResult($puzzleResult);
                $historyRecord->setUser($user);
                $historyRecord->setPosition($position);
                
                $em->persist($historyRecord);
                $em->flush();
	}
}
