<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Position;
use AppBundle\Entity\User;
use AppBundle\Entity\UserRankingHistory;

/**
 * UserRankingHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRankingHistoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function addNewHistoryRecord($data, $user, $position)
	{
		$em = $this->getEntityManager();

		$puzzleResult = ($data->puzzleResult == 'true' || $data->puzzleResult == '1') ? 1 : 0;

                $historyRecord = new UserRankingHistory();
                $historyRecord->setUserRanking($data->newUserRanking);
                $historyRecord->setSolveResult($puzzleResult);
                $historyRecord->setRankingDifference($data->rankingDifference);
                $historyRecord->setUser($user);
                $historyRecord->setPosition($position);

                $em->persist($historyRecord);
                $em->flush();
	}

    public function getUserRankingHistory($idUser, $limit = 10)
    {
       return $this->findByUser($idUser, ['created'=>'DESC'], $limit);
    }
}
