<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Position;
use AppBundle\Entity\User;
use AppBundle\Entity\UserRankingHistory;

/**
 * UserRankingHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRankingHistoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function addNewHistoryRecord(Position $position, User $user, $puzzleResult)
	{
		$em = $this->getEntityManager();

		$puzzleResult = ($puzzleResult == 'true') ? 1 : 0;

        $historyRecord = new UserRankingHistory();
        $historyRecord->setUserRanking($position->getPuzzleRanking());
        $historyRecord->setSolveResult($puzzleResult);
        $historyRecord->setUser($user);
        $historyRecord->setPosition($position);

        $em->persist($historyRecord);
        $em->flush();
	}
}
