# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    app.user.service:
        class: AppBundle\Service\UserService

    app.position.service:
        class: AppBundle\Service\PositionService
        arguments:
            ["@doctrine.orm.entity_manager"]
        public: true

    AppBundle\Stats\AbstractStatsService:
        abstract:  true
        arguments: ['@doctrine.orm.entity_manager']

    app.puzzle.stats.service:
        class: AppBundle\Stats\UserStatsService
        public: true

    app.statistical.service:
        class: AppBundle\Service\StatisticalService

    app.statistical.consumer:
        class: AppBundle\Consumer\StatisticalConsumer
        arguments: ['@monolog.logger.rabbitMQStats', '@doctrine.orm.entity_manager', '@app.statistical.service', '@app.message.service', '@app.user.service', '@app.position.service']
        public: true

    app.message.service:
        class: AppBundle\Service\MessageService

    # makes classes in src/AppBundle/DataFixtures available to be used as services
    # and have a tag that allows actions to type-hint services
    AppBundle\DataFixtures\:
        resource: '../../src/AppBundle/DataFixtures'
        tags: ['doctrine.fixture.orm']
